const productsData = [    
    {
        "name": "Lamb Meal - Puppy All Breeds",
        "brand": "Old Prince",
        "price": 30.5,
        "size": ["small", "medium", "large"],
        "age": ["puppy"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-lambmeal-allbreeds.png"
        },
    {
        "name": "Lamb Meal - Adult Dog Small Breed",
        "brand": "Old Prince",
        "price": 30.5,
        "size": ["small"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-lambmeal-adultsmall.png"
    },
    {
        "name": "Lamb Meal - Adult Dog Medium & Large Breeds",
        "brand": "Old Prince",
        "price": 40.5,
        "size": ["Medium", "Large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-lambmeal-adultmedium.png"
    },
    {   
        "name": "Swine Meal - Adult Dog All Breeds",
        "brand": "Old Prince",
        "price": 20,
        "size": ["small", "medium", "large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-swine-adultall.png"
    },
    {
        "name": "Equilibrium A",
        "brand": "Old Prince",
        "price": 32,
        "size": ["medium", "large"],
        "age": ["puppy"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-equilibriuma.png"
    },
    {
        "name": "Equilibrium B",
        "brand": "Old Prince",
        "price": 25,
        "size": ["small"],
        "age": ["puppy"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-equilibriumb.png"
    },
    {
        "name": "Equilibrium C",
        "brand": "Old Prince",
        "price": 34,
        "size": ["small"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-equilibriumc.png"
    },
    {
        "name": "Equilibrium D",
        "brand": "Old Prince",
        "price": 29,
        "size": ["medium", "large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15],
        "image": "oldprince-equilibriumd.png"
    },
    {
        "name": "Special Recipe",
        "brand": "Old Prince",
        "price": 56,
        "size": ["small", "medium", "large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": true,
        "package-weight": [3, 15],
        "image": "oldprince-weight.png"
    },
    {
        "name": "Salmon Formula Wet",
        "brand": "Hill's",
        "price": 23,
        "size": ["small", "medium", "large"],
        "age": ["adult", "senior"],
        "recovery": false,
        "special diet": true,
        "overweight": true,
        "package-weight": [0.370],
        "image": "hills-salmonwet.jpg"
    },
    {
        "name": "Metabolic Canine Treats",
        "brand": "Hill's",
        "price": 45,
        "size": ["small", "medium", "large"],
        "age": ["adult", "senior"],
        "recovery": false,
        "special diet": false,
        "overweight": true,
        "package-weight": [3, 15],
        "image": "hills-metabolic-treats.jpg"
    },
    {
        "name": "Distinction Canine Beef Recipe",
        "brand": "Nature's Logic",
        "price": 20,
        "size": ["small", "medium", "large"],
        "age": ["puppy", "adult", "senior"],
        "recovery": false,
        "special diet": false,
        "overweight": true,
        "package-weight": [3, 15],
        "image": "natureslogic-canine-beef.png"
    },
    {
        "name": "Canine Rabbit Feast",
        "brand": "Nature's Logic",
        "price": 25,
        "size": ["large"],
        "age": ["senior"],
        "recovery": true,
        "special diet": true,
        "overweight": false,
        "package-weight": [7.5, 15],
        "image": "natureslogic-rabbit-feast.png"
    },
    {
        "name": "Canine Venison Meal Feast",
        "brand": "Nature's Logic",
        "price": 30,
        "size": ["small"],
        "age": ["adult", "senior"],
        "recovery": false,
        "special diet": true,
        "overweight": false,
        "package-weight": [3, 15],
        "image": "natureslogic-venison.png"
    },
    {
        "name": "Canine Duck&Salmon Meal Feast",
        "brand": "Nature's Logic",
        "price": 35,
        "size": ["small", "medium"],
        "age": ["puppy", "adult"],
        "recovery": true,
        "special diet": true,
        "overweight": true,
        "package-weight": [3, 15],
        "image": "natureslogic-duck.png"
    },
]

const featuredProductsData = [
    {
        "name": "Chew Bacon",
        "image": "https://puppis.vteximg.com.br/arquivos/ids/180132-1000-1000/231096.jpg?v=637579992273270000",
        "price": 31.80,
        "type": "#Chewing",
        "id": 230,
    },
    {
        "name": "GoodWood - Coffee Wood",
        "image": "https://www.thenaturalpetstore.co.uk/wp-content/uploads/2020/06/174756908.jpg",
        "price": 31.80,
        "type": "#Chewing",
        "id": 231,
    },
    {
        "name": "EcoKind - Pet Chew",
        "image": "https://m.media-amazon.com/images/I/71eBS9OjX-L._AC_SL1500_.jpg",
        "price": 31.80,
        "type": "#Chewing",
        "id": 232,
    },
    {
        "name": "Rocco's Cow Ear",
        "image": "https://shop-cdn-m.mediazs.com/bilder/rocco/natural/dried/cows/ear/5/400/37451_pla_rocco_driedchews_ears_10chews_1000x1000_5.jpg",
        "price": 31.80,
        "type": "#Chewing",
        "id": 233,
    },
    {
        "name": "Lukullus Junior - Chicken&Lamb",
        "image": "https://shop-cdn-m.mediazs.com/bilder/lukullus/junior/con/corazn/de/pavo/y/cordero/6/400/lk_800g_junior_putelamm_1000x1000_6.jpg",
        "price": 31.80,
        "type": "#Wet",
        "id": 234,
    },
    {
        "name": "Wold of Wilderness - Adult",
        "image": "https://shop-cdn-m.mediazs.com/bilder/wolf/of/wilderness/adult/classic/x/g/0/400/wow_classic_blackrocks_400g_1000px_0.jpg",
        "price": 31.80,
        "type": "#Wet",
        "id": 235,
    },
    {
        "name": "Brit Monot - Protein&Rice",
        "image": "https://brit-petfood.com/file/nodes/product/mainImage/mp_lamb&rice-1.png",
        "price": 31.80,
        "type": "#Wet",
        "id": 236,
    },
    {
        "name": "Rosie's Farm - Chicken&Turkey",
        "image": "https://www.staall.com/web/uploads/prices_products/276/6-x-400g-rosies-farm-wet-dog-food--special-price---c259d6a8d7-large.jpg",
        "price": 31.80,
        "type": "#Wet",
        "id": 237,
    },
    {
        "name": "Csirkemell nyesedék",
        "image": "https://wildbalance.es/wp-content/uploads/2021/07/wild-balance_menu-completo-barf-cordero-verduras-perros_pack.png",
        "price": 31.80,
        "type": "#Barf",
        "id": 238,
    },
    {
        "name": "Graf Barf - Marhamenü",
        "image": "https://barfshopmagyarorszag.cdn.shoprenter.hu/custom/barfshopmagyarorszag/image/cache/w600h600wt1/marhamenu_grafbarf_barfshop.png?lastmod=1646046816.1627308006",
        "price": 31.80,
        "type": "#Barf",
        "id": 239,
    },
    {
        "name": "As Pol - Lóhús",
        "image": "https://cdn.shopify.com/s/files/1/0502/6965/1106/products/rojo_400x.jpg?v=1605454813",
        "price": 31.80,
        "type": "#Barf",
        "id": 240,
    },
    {
        "name": "Prémium vadhús",
        "image": "https://barfshopmagyarorszag.cdn.shoprenter.hu/custom/barfshopmagyarorszag/image/cache/w900h500wt1/Term%C3%A9kek/Fleischeslust/steakvad.png?lastmod=1646058489.1627308006",
        "price": 31.80,
        "type": "#Barf",
        "id": 241,
    },
    {
        "name": "Trixie Premio Sushi Bites Light",
        "image": "https://shop-cdn-m.mediazs.com/bilder/trixie/premio/sushi/bites/light/2/400/36979_pla_trixie_premio_sushi_bites_light_75g_hs_01_2.jpg",
        "price": 31.80,
        "type": "#Treats",
        "id": 242,
    },
    {
        "name": "Royal Canin Educ",
        "image": "https://shop-cdn-m.mediazs.com/bilder/royal/canin/educ/9/400/212977_rc_educ_9.jpg",
        "price": 31.80,
        "type": "#Treats",
        "id": 243,
    },
    {
        "name": "Pedigree Tasty Bites",
        "image": "https://shop-cdn-m.mediazs.com/bilder/pedigree/tasty/bites/2/400/1_74117_pla_mars_pedigree_minihappen_rindkaese_2.jpg",
        "price": 31.80,
        "type": "#Treats",
        "id": 244,
    },
    {
        "name": "Platinum Fit-Sticks",
        "image": "https://www.huellacanina.com/images/platinum-fit-sticks-pollo-conejo.jpg",
        "price": 31.80,
        "type": "#Treats",
        "id": 245,
    },
]