const productsData = [    
    {
        "name": "Lamb Meal - Puppy All Breeds",
        "brand": "Old Prince",
        "price": 30.5,
        "size": ["small", "medium", "large"],
        "age": ["puppy"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
        },
    {
        "name": "Lamb Meal - Adult Dog Small Breed",
        "brand": "Old Prince",
        "price": 30.5,
        "size": ["small"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {
        "name": "Lamb Meal - Adult Dog Medium & Large Breeds",
        "brand": "Old Prince",
        "price": 40.5,
        "size": ["Medium", "Large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {   
        "name": "Swine Meal - Adult Dog All Breeds",
        "brand": "Old Prince",
        "price": 20,
        "size": ["small", "medium", "large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {
        "name": "Equilibrium A",
        "brand": "Old Prince",
        "price": 32,
        "size": ["medium", "large"],
        "age": ["puppy"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {
        "name": "Equilibrium B",
        "brand": "Old Prince",
        "price": 25,
        "size": ["small"],
        "age": ["puppy"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {
        "name": "Equilibrium C",
        "brand": "Old Prince",
        "price": 34,
        "size": ["small"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {
        "name": "Equilibrium D",
        "brand": "Old Prince",
        "price": 29,
        "size": ["medium", "large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": false,
        "package-weight": [3, 7.5, 15]
    },
    {
        "name": "Special Recipe",
        "brand": "Old Prince",
        "price": 56,
        "size": ["small", "medium", "large"],
        "age": ["adult"],
        "recovery": false,
        "special diet": false,
        "overweight": true,
        "package-weight": [3, 15]
    },
    {
        "name": "Salmon Formula Wet",
        "brand": "Hill's",
        "price": 23,
        "size": ["small", "medium", "large"],
        "age": ["adult", "senior"],
        "recovery": false,
        "special diet": true,
        "overweight": true,
        "package-weight": [0.370]
    },
    {
        "name": "Metabolic Canine Treats",
        "brand": "Hill's",
        "price": 45,
        "size": ["small", "medium", "large"],
        "age": ["adult", "senior"],
        "recovery": false,
        "special diet": false,
        "overweight": true,
        "package-weight": [3, 15]
    },
    {
        "name": "Distinction Canine Beef Recipe",
        "brand": "Nature's Logic",
        "price": 20,
        "size": ["small", "medium", "large"],
        "age": ["puppy", "adult", "senior"],
        "recovery": false,
        "special diet": false,
        "overweight": true,
        "package-weight": [3, 15]
    },
    {
        "name": "Canine Rabbit Feast",
        "brand": "Nature's Logic",
        "price": 25,
        "size": ["large"],
        "age": ["senior"],
        "recovery": true,
        "special diet": true,
        "overweight": false,
        "package-weight": [7.5, 15]
    },
    {
        "name": "Canine Venison Meal Feast",
        "brand": "Nature's Logic",
        "price": 30,
        "size": ["small"],
        "age": ["adult", "senior"],
        "recovery": false,
        "special diet": true,
        "overweight": false,
        "package-weight": [3, 15]
    },
    {
        "name": "Canine Duck&Salmon Meal Feast",
        "brand": "Nature's Logic",
        "price": 35,
        "size": ["small", "medium"],
        "age": ["puppy", "adult"],
        "recovery": true,
        "special diet": true,
        "overweight": true,
        "package-weight": [3, 15]
    },
]